### ISSUE TITLE
About last 2 blocks in Week9/point_copy.py 

### ISSUE THREAD

**Issue by senolakkas** [pembeci/ceng2002#1]
We are on process about that code and we've noticed something a bit strange (for us). Output of last 2 blocks is shown on bottom. We couldn't get expected output for deep copy. We thought that they should be same but "W" is different for each.
Can you explain although they are different it is deep copy?
Thank you.

shallow copy
rect1=A green with TP:(0,40,0) BR:(7,0,0) W:7)
rect3=A blue with TP:(0,40,0) BR:(7,0,0) W:9)

deep copy
rect1=A green with TP:(0,40,0) BR:(7,0,0) W:7)
rect4=A pink with TP:(0,60,0) BR:(7,0,0) W:11)

**Comment by pembeci** [comment]
By "they should be same" do you mean W's should be same in `rect3` and `rect4` output? If you are confused as such, it is just that update statements are different in code:

``` python
     rect3.border_width = 9    # W:9
     rect4.border_width = 11   # W:11
```

If you mean you were expecting `rect1` and `rect4` output to be same in terms of W at the deep copy part then it means you didn't understand what deep copy is doing. Please clarify, if your confusion was smt else.

**Comment by senolakkas** [comment]
At the last block, if "rect4 = deepcopy(rect1)" is deepcopy it has to do same work with "rect2 = rect1".

Output of rect2 = rect1 is:
rect1=A green with TP:(0,20,0) BR:(7,0,0) W:7)
rect2=A green with TP:(0,20,0) BR:(7,0,0) W:7)

Output of rect4 = deepcopy(rect1) is:
rect1=A green with TP:(0,40,0) BR:(7,0,0) W:7)
rect4=A pink with TP:(0,60,0) BR:(7,0,0) W:11)

If second one is a deepcopy why rect1 doesn't change when we modify rect4. We thought that there's a reference copy so that rect1 has to change with rect4.

**Comment by senolakkas** [comment]
As we understand we cannot deep copy objects in deepcopy method, just copy classes and modules.

**Comment by pembeci** [comment]
`rect4 = rect1` creates a reference (alias) to `rect1` so updates to `rect4` is actually updates to `rect1`. If you don't want this behavior -i.e. want to change `rect4`without changing `rect1`\- then you need to clone the object. That's what `deepcopy`does in Python. So modifying `rect4` doesn't modify `rect1` even for references in `rect1` like `top_left_point` since that point is also cloned while creating `rect4`.
